/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedEnrollmentsRouteImport } from './routes/_authenticated/enrollments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedClassesNewRouteImport } from './routes/_authenticated/classes/new'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes/$classId'
import { Route as AuthenticatedClassesClassIdStudentsRouteImport } from './routes/_authenticated/classes/$classId/students'
import { Route as AuthenticatedClassesClassIdSchedulesRouteImport } from './routes/_authenticated/classes/$classId/schedules'
import { Route as AuthenticatedClassesClassIdInvitationsRouteImport } from './routes/_authenticated/classes/$classId/invitations'
import { Route as AuthenticatedClassesClassIdAnnouncementsRouteImport } from './routes/_authenticated/classes/$classId/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnrollmentsRoute =
  AuthenticatedEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesNewRoute = AuthenticatedClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdStudentsRoute =
  AuthenticatedClassesClassIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)
const AuthenticatedClassesClassIdSchedulesRoute =
  AuthenticatedClassesClassIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)
const AuthenticatedClassesClassIdInvitationsRoute =
  AuthenticatedClassesClassIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)
const AuthenticatedClassesClassIdAnnouncementsRoute =
  AuthenticatedClassesClassIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enrollments': typeof AuthenticatedEnrollmentsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/join/$token': typeof JoinTokenRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/announcements': typeof AuthenticatedClassesClassIdAnnouncementsRoute
  '/classes/$classId/invitations': typeof AuthenticatedClassesClassIdInvitationsRoute
  '/classes/$classId/schedules': typeof AuthenticatedClassesClassIdSchedulesRoute
  '/classes/$classId/students': typeof AuthenticatedClassesClassIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enrollments': typeof AuthenticatedEnrollmentsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/join/$token': typeof JoinTokenRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/announcements': typeof AuthenticatedClassesClassIdAnnouncementsRoute
  '/classes/$classId/invitations': typeof AuthenticatedClassesClassIdInvitationsRoute
  '/classes/$classId/schedules': typeof AuthenticatedClassesClassIdSchedulesRoute
  '/classes/$classId/students': typeof AuthenticatedClassesClassIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enrollments': typeof AuthenticatedEnrollmentsRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/_authenticated/classes/new': typeof AuthenticatedClassesNewRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/classes/$classId/announcements': typeof AuthenticatedClassesClassIdAnnouncementsRoute
  '/_authenticated/classes/$classId/invitations': typeof AuthenticatedClassesClassIdInvitationsRoute
  '/_authenticated/classes/$classId/schedules': typeof AuthenticatedClassesClassIdSchedulesRoute
  '/_authenticated/classes/$classId/students': typeof AuthenticatedClassesClassIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/enrollments'
    | '/feedback'
    | '/notifications'
    | '/join/$token'
    | '/classes/$classId'
    | '/classes/new'
    | '/classes/'
    | '/classes/$classId/announcements'
    | '/classes/$classId/invitations'
    | '/classes/$classId/schedules'
    | '/classes/$classId/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/enrollments'
    | '/feedback'
    | '/notifications'
    | '/join/$token'
    | '/classes/$classId'
    | '/classes/new'
    | '/classes'
    | '/classes/$classId/announcements'
    | '/classes/$classId/invitations'
    | '/classes/$classId/schedules'
    | '/classes/$classId/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/enrollments'
    | '/_authenticated/feedback'
    | '/_authenticated/notifications'
    | '/join/$token'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/classes/new'
    | '/_authenticated/classes/'
    | '/_authenticated/classes/$classId/announcements'
    | '/_authenticated/classes/$classId/invitations'
    | '/_authenticated/classes/$classId/schedules'
    | '/_authenticated/classes/$classId/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollments': {
      id: '/_authenticated/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof AuthenticatedEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/new': {
      id: '/_authenticated/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof AuthenticatedClassesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId/students': {
      id: '/_authenticated/classes/$classId/students'
      path: '/students'
      fullPath: '/classes/$classId/students'
      preLoaderRoute: typeof AuthenticatedClassesClassIdStudentsRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
    '/_authenticated/classes/$classId/schedules': {
      id: '/_authenticated/classes/$classId/schedules'
      path: '/schedules'
      fullPath: '/classes/$classId/schedules'
      preLoaderRoute: typeof AuthenticatedClassesClassIdSchedulesRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
    '/_authenticated/classes/$classId/invitations': {
      id: '/_authenticated/classes/$classId/invitations'
      path: '/invitations'
      fullPath: '/classes/$classId/invitations'
      preLoaderRoute: typeof AuthenticatedClassesClassIdInvitationsRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
    '/_authenticated/classes/$classId/announcements': {
      id: '/_authenticated/classes/$classId/announcements'
      path: '/announcements'
      fullPath: '/classes/$classId/announcements'
      preLoaderRoute: typeof AuthenticatedClassesClassIdAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
  }
}

interface AuthenticatedClassesClassIdRouteChildren {
  AuthenticatedClassesClassIdAnnouncementsRoute: typeof AuthenticatedClassesClassIdAnnouncementsRoute
  AuthenticatedClassesClassIdInvitationsRoute: typeof AuthenticatedClassesClassIdInvitationsRoute
  AuthenticatedClassesClassIdSchedulesRoute: typeof AuthenticatedClassesClassIdSchedulesRoute
  AuthenticatedClassesClassIdStudentsRoute: typeof AuthenticatedClassesClassIdStudentsRoute
}

const AuthenticatedClassesClassIdRouteChildren: AuthenticatedClassesClassIdRouteChildren =
  {
    AuthenticatedClassesClassIdAnnouncementsRoute:
      AuthenticatedClassesClassIdAnnouncementsRoute,
    AuthenticatedClassesClassIdInvitationsRoute:
      AuthenticatedClassesClassIdInvitationsRoute,
    AuthenticatedClassesClassIdSchedulesRoute:
      AuthenticatedClassesClassIdSchedulesRoute,
    AuthenticatedClassesClassIdStudentsRoute:
      AuthenticatedClassesClassIdStudentsRoute,
  }

const AuthenticatedClassesClassIdRouteWithChildren =
  AuthenticatedClassesClassIdRoute._addFileChildren(
    AuthenticatedClassesClassIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnrollmentsRoute: typeof AuthenticatedEnrollmentsRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRouteWithChildren
  AuthenticatedClassesNewRoute: typeof AuthenticatedClassesNewRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnrollmentsRoute: AuthenticatedEnrollmentsRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedClassesClassIdRoute:
    AuthenticatedClassesClassIdRouteWithChildren,
  AuthenticatedClassesNewRoute: AuthenticatedClassesNewRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
